# Generated by Django 3.0.4 on 2020-03-07 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='chat_session',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='name',
        ),
        migrations.AddField(
            model_name='chatsession',
            name='title',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='chat_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.ChatSession'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
