# Generated by Django 3.0.6 on 2020-05-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200307_0451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='bot',
        ),
        migrations.RemoveField(
            model_name='message',
            name='chat_session',
        ),
        migrations.RemoveField(
            model_name='message',
            name='created_at',
        ),
        migrations.AddField(
            model_name='message',
            name='send_to',
            field=models.CharField(default='', max_length=25),
        ),
    ]
